[package]
name = "dlux_metadata_pm"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.59.1" }

[addresses]
dlux = "0x0"
